#!/usr/bin/env python3
"""Supplemental end-to-end workflow verification test (Requirement 13).

This module is the **optional** (`*`) test named in Task 16.1. Per
Requirement 12.11, it is the one test in the suite allowed to remain
optional, because it requires runtime agent behavior (live `kiro-cli`
reviewer judgment) that is difficult to automate reliably. It supplements,
and does not replace, the mandatory fixture/integration test modules from
Tasks 4, 5, 13, and 14 (`tests/test_security_reviewer.py`,
`tests/test_reliability_reviewer.py`, `tests/test_baseline_pass.py`,
`tests/test_remediation_script.py`, `tests/test_remediated_plan.py`).

What this module adds beyond those mandatory modules: it walks the full
`baseline -> candidate -> CHANGE_BLOCKED -> approve -> remediate ->
remediated -> SAFE_TO_SHIP` judge-walkthrough wiring (design.md's Testing
Strategy, Requirement 13.1/13.2) against a real, temporary copy of
`terraform/main.tf`, once per each of the four supported rule IDs
(`SEC-001`, `SEC-002`, `REL-001`, `BR-001`) in turn, and additionally
exercises the rejection branch once.

Guards, mirroring the sibling integration test modules exactly
(`tests/test_remediated_plan.py`, `tests/test_remediation_script.py`,
`tests/test_baseline_pass.py`):

    - The whole class requires a real `terraform` binary on `PATH`
      (`unittest.skipUnless(shutil.which("terraform"), ...)`), since every
      scenario here generates real Terraform plan JSON from a real,
      temporary Terraform working copy. No part of this module ever runs
      `terraform apply`, `terraform destroy`, or any AWS CLI command --
      only the same `init`/`fmt`/`validate`/`plan`/`show` pipeline
      `scripts/run_tf_plan.py` itself is restricted to.
    - The four full-cycle scenario tests (one per rule ID), which assert a
      live `CHANGE_BLOCKED`-equivalent verdict and a live
      `SAFE_TO_SHIP`-equivalent verdict from the real Security Reviewer /
      Reliability Reviewer agents, additionally require a live `kiro-cli`
      binary, honoring `CHANGEGUARD_SKIP_LIVE_TESTS` exactly like
      `tests/test_baseline_pass.py` (`make test` sets that env var so the
      fast suite never spends Kiro credits; `make test-live` does not).
    - The rejection-path test requires only `terraform`, not `kiro-cli`:
      the "given a `CHANGE_BLOCKED`-equivalent result, simulate rejection"
      assertion is deterministic (it only checks that `apply_remediation.py`
      was never invoked and that the temporary `main.tf` still holds the
      injected candidate value), so it does not need a second live agent
      call to re-derive a verdict already covered by the four scenario
      tests above.

Remediation is always performed via the real `scripts/apply_remediation.py`
CLI script -- "simulating approval" means invoking that deterministic
script with the finding's recorded baseline value, exactly as the
Remediator agent does (`.kiro/agents/remediator-prompt.md`); this module
never calls `terraform apply`/`terraform destroy` or any AWS CLI command,
per `.kiro/steering/changeguard-principles.md`.

The real repository `terraform/main.tf` is never opened for writing
anywhere in this module: the Baseline Plan is generated by pointing
`run_tf_plan.py` at the real, unmodified `terraform/` directory (which only
reads `main.tf`), and every step that injects a candidate transition or
performs remediation operates on a fresh temporary copy of the whole
`terraform/` directory instead.

Uses only the Python 3 standard library `unittest` module for the test
framework itself; `terraform` and `kiro-cli` are external CLI dependencies
of the product under test, not Python test dependencies.
"""

import functools
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TERRAFORM_DIR = os.path.join(REPO_ROOT, "terraform")
APPLY_REMEDIATION_SCRIPT = os.path.join(REPO_ROOT, "scripts", "apply_remediation.py")
RUN_TF_PLAN_SCRIPT = os.path.join(REPO_ROOT, "scripts", "run_tf_plan.py")

TERRAFORM_BIN = shutil.which("terraform")
# `CHANGEGUARD_SKIP_LIVE_TESTS=1` (set by `make test`, the fast/deterministic
# default) forces the live-agent scenario tests below to skip even when
# `kiro-cli` is on PATH, so the fast suite never makes a real,
# credit-consuming LLM call. `make test-live` runs without that env var set.
KIRO_CLI = None if os.environ.get("CHANGEGUARD_SKIP_LIVE_TESTS") else shutil.which("kiro-cli")

_ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-9;]*[a-zA-Z]")

_SCRIPT_TIMEOUT_SECONDS = 120
_AGENT_TIMEOUT_SECONDS = 90

# One entry per supported rule ID, describing exactly how to inject that
# rule's candidate transition into a pristine copy of `terraform/main.tf`
# (mirroring the exact transitions already used by
# `tests/test_remediation_script.py` and `tests/test_remediated_plan.py`),
# which reviewer agent owns judging that rule, which reviewer agent is
# expected to remain unaffected (and therefore PASS) on the same candidate,
# and the exact `--restore-value` `apply_remediation.py` expects to restore
# the baseline.
RULE_SCENARIOS = {
    "SEC-001": {
        "resource": "aws_security_group.payments_sg",
        "owning_reviewer": "security-reviewer",
        "other_reviewer": "reliability-reviewer",
        "anchor": "Internal SSH access",
        "old": 'cidr_blocks = ["10.0.0.0/8"]',
        "new": 'cidr_blocks = ["0.0.0.0/0"]',
        "restore_value": "10.0.0.0/8",
    },
    "SEC-002": {
        "resource": "aws_security_group.payments_sg",
        "owning_reviewer": "security-reviewer",
        "other_reviewer": "reliability-reviewer",
        "anchor": "Internal Postgres access",
        "old": 'cidr_blocks = ["10.0.0.0/8"]',
        "new": 'cidr_blocks = ["0.0.0.0/0"]',
        "restore_value": "10.0.0.0/8",
    },
    "REL-001": {
        "resource": "aws_ecs_service.payments_api",
        "owning_reviewer": "reliability-reviewer",
        "other_reviewer": "security-reviewer",
        "old": "desired_count       = 3",
        "new": "desired_count       = 1",
        "restore_value": "3",
    },
    "BR-001": {
        "resource": "aws_db_instance.payments_db",
        "owning_reviewer": "reliability-reviewer",
        "other_reviewer": "security-reviewer",
        "old": "deletion_protection = true",
        "new": "deletion_protection = false",
        "restore_value": "true",
    },
}


def _replace_after_anchor(content, anchor, old, new):
    """Replace the first occurrence of `old` that appears after `anchor`.

    Mirrors `tests/test_remediation_script.py`'s helper of the same name,
    used to target one of two otherwise identical `cidr_blocks = [...]`
    lines (port 22 vs. port 5432) by the unique description text preceding
    each ingress block.
    """
    anchor_index = content.index(anchor)
    old_index = content.index(old, anchor_index)
    return content[:old_index] + new + content[old_index + len(old):]


def _inject_candidate_transition(pristine_content, rule_id):
    """Return `pristine_content` with the given rule ID's candidate
    transition injected, and nothing else changed."""
    scenario = RULE_SCENARIOS[rule_id]
    if "anchor" in scenario:
        injected = _replace_after_anchor(
            pristine_content, scenario["anchor"], scenario["old"], scenario["new"]
        )
    else:
        injected = pristine_content.replace(scenario["old"], scenario["new"])
    assert injected != pristine_content, (
        f"expected fixture string for {rule_id} to be present in the real main.tf"
    )
    return injected


def _make_temp_terraform_copy(prefix):
    """Create a fresh temporary copy of the whole `terraform/` directory
    (main.tf, versions.tf, the lock file, and the cached provider plugin
    directory if present), and return the temp dir path.

    The real repository `terraform/main.tf` is only ever opened for
    reading here -- never for writing.
    """
    tmp_dir = tempfile.mkdtemp(prefix=prefix)
    for filename in ("main.tf", "versions.tf", ".terraform.lock.hcl"):
        shutil.copyfile(
            os.path.join(TERRAFORM_DIR, filename), os.path.join(tmp_dir, filename)
        )
    cached_provider_dir = os.path.join(TERRAFORM_DIR, ".terraform")
    if os.path.isdir(cached_provider_dir):
        shutil.copytree(cached_provider_dir, os.path.join(tmp_dir, ".terraform"))
    return tmp_dir


def _run_python_script(script_path, args):
    """Run a project CLI script as a real subprocess (never a shell string
    and never an in-process import call), mirroring
    `tests/test_remediation_script.py`'s subprocess convention."""
    return subprocess.run(
        [sys.executable, script_path] + list(args),
        capture_output=True,
        text=True,
        timeout=_SCRIPT_TIMEOUT_SECONDS,
    )


def _generate_plan(terraform_dir, output_path):
    return _run_python_script(
        RUN_TF_PLAN_SCRIPT,
        ["--terraform-dir", terraform_dir, "--output", output_path],
    )


@functools.lru_cache(maxsize=None)
def _invoke_reviewer(agent_name, baseline_path, candidate_path):
    """Invoke a live ChangeGuard reviewer agent for one comparison cycle
    and parse its final JSON verdict.

    Mirrors `tests/test_remediated_plan.py`'s helper of the same name.
    Raises `AssertionError` if the agent produced no parseable trailing
    JSON object, since each reviewer's prompt contract requires its final
    chat message to be exactly one JSON object and nothing else. Cached
    (per unique `(agent_name, baseline_path, candidate_path)` tuple) purely
    to avoid redundant live subprocess invocations -- every temporary path
    used by this module is unique per scenario, so caching never mixes
    results across scenarios.
    """
    prompt = (
        f"Baseline plan path: {baseline_path}. "
        f"Candidate plan path: {candidate_path}. "
        "Perform your review."
    )
    result = subprocess.run(
        [KIRO_CLI, "chat", "--agent", agent_name, "--no-interactive", prompt],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=_AGENT_TIMEOUT_SECONDS,
    )
    clean_stdout = _ANSI_ESCAPE_RE.sub("", result.stdout)
    json_start = clean_stdout.rfind('{"agent"')
    if json_start == -1:
        raise AssertionError(
            f"{agent_name} agent produced no trailing JSON verdict object.\n"
            f"returncode={result.returncode}\nstdout={clean_stdout!r}\n"
            f"stderr={_ANSI_ESCAPE_RE.sub('', result.stderr)!r}"
        )
    return json.loads(clean_stdout[json_start:])


@unittest.skipUnless(
    TERRAFORM_BIN,
    "terraform binary not found on PATH; skipping the supplemental "
    "end-to-end workflow verification test (Requirement 13, optional "
    "per Requirement 12.11).",
)
class EndToEndWorkflowTests(unittest.TestCase):
    """Requirement 13's judge walkthrough, exercised once per supported
    rule ID plus the rejection branch, against a real, temporary Terraform
    working copy. Optional per Requirement 12.11."""

    @classmethod
    def setUpClass(cls):
        # One shared Baseline Plan, generated from the real, unmodified
        # terraform/ directory -- never written to by this module -- reused
        # by every scenario below, since it does not depend on which rule's
        # candidate transition is being exercised.
        cls.shared_tmp_dir = tempfile.mkdtemp(prefix="test_e2e_workflow_shared_")
        cls.baseline_plan_path = os.path.join(cls.shared_tmp_dir, "baseline-plan.json")
        baseline_result = _generate_plan(TERRAFORM_DIR, cls.baseline_plan_path)
        assert baseline_result.returncode == 0, (
            f"baseline plan generation failed: {baseline_result.stderr}"
        )

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.shared_tmp_dir, ignore_errors=True)

    def _run_full_cycle_for_rule(self, rule_id):
        """Walk baseline -> candidate -> CHANGE_BLOCKED-equivalent ->
        approve -> remediate -> remediated -> SAFE_TO_SHIP-equivalent for
        one rule ID, against a fresh temporary Terraform working copy."""
        scenario = RULE_SCENARIOS[rule_id]
        tmp_dir = _make_temp_terraform_copy(prefix=f"test_e2e_{rule_id}_")
        self.addCleanup(shutil.rmtree, tmp_dir, ignore_errors=True)
        main_tf_path = os.path.join(tmp_dir, "main.tf")

        with open(main_tf_path) as main_tf_file:
            pristine_content = main_tf_file.read()
        candidate_content = _inject_candidate_transition(pristine_content, rule_id)
        with open(main_tf_path, "w") as main_tf_file:
            main_tf_file.write(candidate_content)

        # --- candidate plan ---------------------------------------------
        candidate_plan_path = os.path.join(tmp_dir, "candidate-plan.json")
        candidate_result = _generate_plan(tmp_dir, candidate_plan_path)
        self.assertEqual(
            candidate_result.returncode, 0,
            msg=f"candidate plan generation failed: {candidate_result.stderr}",
        )

        # --- CHANGE_BLOCKED-equivalent: exactly one FAIL with rule_id ----
        owning_verdict = _invoke_reviewer(
            scenario["owning_reviewer"], self.baseline_plan_path, candidate_plan_path
        )
        other_verdict = _invoke_reviewer(
            scenario["other_reviewer"], self.baseline_plan_path, candidate_plan_path
        )
        self.assertEqual(
            owning_verdict.get("status"), "FAIL",
            msg=f"expected {scenario['owning_reviewer']} to FAIL for {rule_id}: {owning_verdict}",
        )
        owning_rule_ids = {
            finding.get("rule_id") for finding in owning_verdict.get("findings", [])
        }
        self.assertIn(rule_id, owning_rule_ids)
        self.assertEqual(
            other_verdict.get("status"), "PASS",
            msg=f"expected {scenario['other_reviewer']} to PASS for {rule_id}: {other_verdict}",
        )
        self.assertEqual(other_verdict.get("findings", []), [])

        # --- simulate approval: invoke apply_remediation.py directly ----
        remediation_result = _run_python_script(
            APPLY_REMEDIATION_SCRIPT,
            [
                "--terraform-dir", tmp_dir,
                "--rule-id", rule_id,
                "--resource", scenario["resource"],
                "--restore-value", scenario["restore_value"],
            ],
        )
        self.assertEqual(
            remediation_result.returncode, 0,
            msg=f"apply_remediation.py failed for {rule_id}: {remediation_result.stderr}",
        )
        with open(main_tf_path) as main_tf_file:
            remediated_content = main_tf_file.read()
        self.assertEqual(remediated_content, pristine_content)

        # --- remediated plan ---------------------------------------------
        remediated_plan_path = os.path.join(tmp_dir, "remediated-plan.json")
        remediated_result = _generate_plan(tmp_dir, remediated_plan_path)
        self.assertEqual(
            remediated_result.returncode, 0,
            msg=f"remediated plan generation failed: {remediated_result.stderr}",
        )

        # --- SAFE_TO_SHIP-equivalent: both reviewers PASS ----------------
        owning_final_verdict = _invoke_reviewer(
            scenario["owning_reviewer"], self.baseline_plan_path, remediated_plan_path
        )
        other_final_verdict = _invoke_reviewer(
            scenario["other_reviewer"], self.baseline_plan_path, remediated_plan_path
        )
        self.assertEqual(owning_final_verdict.get("status"), "PASS")
        self.assertEqual(owning_final_verdict.get("findings", []), [])
        self.assertEqual(other_final_verdict.get("status"), "PASS")
        self.assertEqual(other_final_verdict.get("findings", []), [])

    @unittest.skipUnless(
        KIRO_CLI,
        "kiro-cli is not on PATH (or CHANGEGUARD_SKIP_LIVE_TESTS is set); "
        "skipping the live-agent SEC-001 end-to-end cycle.",
    )
    def test_sec001_full_cycle(self):
        self._run_full_cycle_for_rule("SEC-001")

    @unittest.skipUnless(
        KIRO_CLI,
        "kiro-cli is not on PATH (or CHANGEGUARD_SKIP_LIVE_TESTS is set); "
        "skipping the live-agent SEC-002 end-to-end cycle.",
    )
    def test_sec002_full_cycle(self):
        self._run_full_cycle_for_rule("SEC-002")

    @unittest.skipUnless(
        KIRO_CLI,
        "kiro-cli is not on PATH (or CHANGEGUARD_SKIP_LIVE_TESTS is set); "
        "skipping the live-agent REL-001 end-to-end cycle.",
    )
    def test_rel001_full_cycle(self):
        self._run_full_cycle_for_rule("REL-001")

    @unittest.skipUnless(
        KIRO_CLI,
        "kiro-cli is not on PATH (or CHANGEGUARD_SKIP_LIVE_TESTS is set); "
        "skipping the live-agent BR-001 end-to-end cycle.",
    )
    def test_br001_full_cycle(self):
        self._run_full_cycle_for_rule("BR-001")

    def test_rejection_path_leaves_main_tf_unmodified_and_never_remediates(self):
        """REMEDIATION_REJECTED-equivalent: given a CHANGE_BLOCKED-equivalent
        candidate (the SEC-001 transition injected below is exactly the
        transition `test_sec001_full_cycle` asserts produces a live
        `FAIL`/`SEC-001` verdict), "simulating rejection" means simply never
        invoking `apply_remediation.py`. This assertion is deterministic --
        it does not require a second live agent call, since it only checks
        that the temporary `main.tf` still holds the injected candidate
        value (i.e. nothing remediated it) and that no remediation artifact
        was produced.
        """
        rule_id = "SEC-001"
        scenario = RULE_SCENARIOS[rule_id]
        tmp_dir = _make_temp_terraform_copy(prefix="test_e2e_rejection_")
        self.addCleanup(shutil.rmtree, tmp_dir, ignore_errors=True)
        main_tf_path = os.path.join(tmp_dir, "main.tf")

        with open(main_tf_path) as main_tf_file:
            pristine_content = main_tf_file.read()
        candidate_content = _inject_candidate_transition(pristine_content, rule_id)
        with open(main_tf_path, "w") as main_tf_file:
            main_tf_file.write(candidate_content)

        candidate_plan_path = os.path.join(tmp_dir, "candidate-plan.json")
        candidate_result = _generate_plan(tmp_dir, candidate_plan_path)
        self.assertEqual(
            candidate_result.returncode, 0,
            msg=f"candidate plan generation failed: {candidate_result.stderr}",
        )

        # Simulate rejection: do nothing further. apply_remediation.py is
        # never invoked on this temporary directory in this test.
        with open(main_tf_path) as main_tf_file:
            after_rejection_content = main_tf_file.read()
        self.assertEqual(after_rejection_content, candidate_content)
        self.assertIn(scenario["new"], after_rejection_content)
        self.assertNotEqual(after_rejection_content, pristine_content)


if __name__ == "__main__":
    unittest.main()
