#!/usr/bin/env python3
"""Remediated Plan PASS test (Requirements 12.8, 12.10).

This module verifies the full remediation-and-re-review round trip end to
end against real Terraform, not fixtures: starting from a temporary copy of
the actual repository `terraform/main.tf` with one Security Reviewer-scoped
transition (SEC-001) and one Reliability Reviewer-scoped transition
(REL-001) injected, it runs the real `scripts/apply_remediation.py` to
correct both, runs the real `scripts/run_tf_plan.py` to produce a genuine
Remediated Plan JSON artifact from real Terraform output, and then asserts
that both the Security Reviewer and the Reliability Reviewer return
`status: PASS` with an empty `findings` list when comparing the Baseline
Plan (generated from the unmodified `terraform/main.tf`) against that
Remediated Plan.

Why this test invokes a live `kiro-cli` agent, not a plain Python function:
exactly as documented in `tests/test_baseline_pass.py`, the rule-satisfaction
judgment step that produces `PASS`/`FAIL`/`INCOMPLETE` lives entirely inside
each reviewer agent's own LLM system prompt
(`.kiro/agents/security-reviewer-prompt.md` and
`.kiro/agents/reliability-reviewer-prompt.md`), driven by the agent
definitions at `.kiro/agents/security-reviewer.json` and
`.kiro/agents/reliability-reviewer.json` (Tasks 8.1/8.2). There is no plain,
directly-importable Python function anywhere in this repository that
returns a `ReviewResult`/`PASS`/`FAIL`/`INCOMPLETE` verdict -- the
deterministic evidence-extraction modules
(`scripts/security_rules.py`, `scripts/reliability_rules.py`) explicitly
document that judging whether extracted evidence is acceptable is out of
their scope. Asserting a live `PASS` verdict for the Remediated Plan
therefore requires invoking each reviewer via
`kiro-cli chat --agent <name> --no-interactive`, the same invocation used to
verify the agent definitions during Tasks 8.1/8.2 and by
`tests/test_baseline_pass.py`, `tests/test_security_reviewer.py`, and
`tests/test_reliability_reviewer.py`.

Two independent, layered guards are used, consistent with the sibling
integration test modules:

    - The whole class is guarded with
      `unittest.skipUnless(shutil.which("terraform"), ...)`, per the task
      instructions and design.md's Testing Strategy, since generating a
      real Baseline Plan and a real Remediated Plan requires the actual
      Terraform binary (and the cached AWS provider) -- no part of this
      module invokes `terraform apply`, `terraform destroy`, or any AWS CLI
      command; only the `init`/`fmt`/`validate`/`plan`/`show` allow-listed
      subcommands `scripts/run_tf_plan.py` itself invokes are ever run.
    - The two live-agent PASS-verdict test methods are additionally guarded
      with `unittest.skipUnless(shutil.which("kiro-cli"), ...)`, mirroring
      `tests/test_baseline_pass.py`, so that in a terraform-only environment
      (no live agent runtime available) the deterministic portion of this
      test -- that real remediation genuinely restored the baseline values
      in a temporary copy of `main.tf`, and that a real Remediated Plan
      artifact was produced -- still runs and still provides useful
      coverage, while only the verdict-level PASS assertions are skipped.

The real repository `terraform/main.tf` is never modified: the Baseline
Plan is generated by pointing `run_tf_plan.py` at the real, unmodified
`terraform/` directory (which only reads `main.tf`; nothing in this module
writes to it), and every remediation/plan-generation step that could not
tolerate a mutated file operates on a fresh temporary copy of the whole
`terraform/` directory instead.

Uses only the Python 3 standard library `unittest` module for the test
framework itself; `terraform` and `kiro-cli` are external CLI dependencies
of the product under test, not Python test dependencies.
"""

import functools
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TERRAFORM_DIR = os.path.join(REPO_ROOT, "terraform")
APPLY_REMEDIATION_SCRIPT = os.path.join(REPO_ROOT, "scripts", "apply_remediation.py")
RUN_TF_PLAN_SCRIPT = os.path.join(REPO_ROOT, "scripts", "run_tf_plan.py")

TERRAFORM_BIN = shutil.which("terraform")
# `CHANGEGUARD_SKIP_LIVE_TESTS=1` (set by `make test`, the fast/deterministic
# default) forces the live-agent PASS-verdict tests below to skip even when
# `kiro-cli` is on PATH, so the fast suite never makes a real,
# credit-consuming LLM call. `make test-live` runs without that env var set.
KIRO_CLI = None if os.environ.get("CHANGEGUARD_SKIP_LIVE_TESTS") else shutil.which("kiro-cli")

_ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-9;]*[a-zA-Z]")

_SCRIPT_TIMEOUT_SECONDS = 120
_AGENT_TIMEOUT_SECONDS = 90


def _run_python_script(script_path, args):
    """Run a project CLI script as a real subprocess (never a shell string).

    Mirrors `tests/test_remediation_script.py`'s subprocess convention: the
    exact CLI invocation a human/agent would use, never an in-process import
    call, so this exercises the real argv/exit-code contract.
    """
    return subprocess.run(
        [sys.executable, script_path] + list(args),
        capture_output=True,
        text=True,
        timeout=_SCRIPT_TIMEOUT_SECONDS,
    )


@functools.lru_cache(maxsize=None)
def _invoke_reviewer(agent_name, baseline_path, candidate_path):
    """Invoke a live ChangeGuard reviewer agent for one comparison cycle
    and parse its final JSON verdict.

    Raises `AssertionError` if the agent produced no parseable trailing
    JSON object, since each reviewer's prompt contract requires its final
    chat message to be exactly one JSON object and nothing else.

    Cached (per unique `(agent_name, baseline_path, candidate_path)` tuple,
    for the lifetime of the test process) via `functools.lru_cache` purely
    to avoid redundant live subprocess invocations if this helper is ever
    called more than once with the same arguments - the underlying agent
    invocation itself is always genuine and is never stubbed or faked.
    """
    prompt = (
        f"Baseline plan path: {baseline_path}. "
        f"Candidate plan path: {candidate_path}. "
        "Perform your review."
    )
    result = subprocess.run(
        [KIRO_CLI, "chat", "--agent", agent_name, "--no-interactive", prompt],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=_AGENT_TIMEOUT_SECONDS,
    )
    clean_stdout = _ANSI_ESCAPE_RE.sub("", result.stdout)
    json_start = clean_stdout.rfind('{"agent"')
    if json_start == -1:
        raise AssertionError(
            f"{agent_name} agent produced no trailing JSON verdict object.\n"
            f"returncode={result.returncode}\nstdout={clean_stdout!r}\n"
            f"stderr={_ANSI_ESCAPE_RE.sub('', result.stderr)!r}"
        )
    return json.loads(clean_stdout[json_start:])


@unittest.skipUnless(
    TERRAFORM_BIN,
    "terraform binary not found on PATH; skipping the real-Terraform "
    "Remediated Plan PASS integration test (Requirement 12.8).",
)
class RemediatedPlanPassTests(unittest.TestCase):
    """Requirement 12.8: a real Remediated Plan, generated by real
    Terraform after a real remediation, produces `PASS` from both
    reviewers when compared against the Baseline Plan."""

    @classmethod
    def setUpClass(cls):
        cls.tmp_dir = tempfile.mkdtemp(prefix="test_remediated_plan_")

        # Fresh temporary copy of the Terraform configuration -- the real
        # terraform/main.tf is never opened for writing anywhere in this
        # module.
        for filename in ("main.tf", "versions.tf", ".terraform.lock.hcl"):
            shutil.copyfile(
                os.path.join(TERRAFORM_DIR, filename),
                os.path.join(cls.tmp_dir, filename),
            )

        # Reuse the repository's cached provider plugin, if present, so
        # this test doesn't require network access to the Terraform
        # registry. If no cache is present, `terraform init` below falls
        # back to downloading the provider itself.
        cached_provider_dir = os.path.join(TERRAFORM_DIR, ".terraform")
        if os.path.isdir(cached_provider_dir):
            shutil.copytree(
                cached_provider_dir, os.path.join(cls.tmp_dir, ".terraform")
            )

        main_tf_path = os.path.join(cls.tmp_dir, "main.tf")
        with open(main_tf_path) as main_tf_file:
            pristine_content = main_tf_file.read()

        # Inject one Security Reviewer-scoped transition (SEC-001) and one
        # Reliability Reviewer-scoped transition (REL-001), so a genuine
        # PASS from *both* reviewers on the remediated result actually
        # reflects real evidence relevant to each reviewer's rule scope,
        # not an unchanged/vacuous comparison.
        injected_content = pristine_content.replace(
            'from_port   = 22\n    to_port     = 22\n    protocol    = "tcp"\n'
            '    cidr_blocks = ["10.0.0.0/8"]',
            'from_port   = 22\n    to_port     = 22\n    protocol    = "tcp"\n'
            '    cidr_blocks = ["0.0.0.0/0"]',
        ).replace(
            "desired_count       = 3",
            "desired_count       = 1",
        )
        assert injected_content != pristine_content, (
            "expected fixture strings to be present in the real main.tf"
        )
        with open(main_tf_path, "w") as main_tf_file:
            main_tf_file.write(injected_content)

        # Apply real remediation for both injected rules against the
        # temporary copy only.
        sec001_result = _run_python_script(
            APPLY_REMEDIATION_SCRIPT,
            [
                "--terraform-dir", cls.tmp_dir,
                "--rule-id", "SEC-001",
                "--resource", "aws_security_group.payments_sg",
                "--restore-value", "10.0.0.0/8",
            ],
        )
        assert sec001_result.returncode == 0, (
            f"SEC-001 remediation failed: {sec001_result.stderr}"
        )

        rel001_result = _run_python_script(
            APPLY_REMEDIATION_SCRIPT,
            [
                "--terraform-dir", cls.tmp_dir,
                "--rule-id", "REL-001",
                "--resource", "aws_ecs_service.payments_api",
                "--restore-value", "3",
            ],
        )
        assert rel001_result.returncode == 0, (
            f"REL-001 remediation failed: {rel001_result.stderr}"
        )

        with open(main_tf_path) as main_tf_file:
            cls.remediated_main_tf_content = main_tf_file.read()

        # Baseline Plan: generated from the real, unmodified terraform/
        # directory -- never the temporary copy.
        cls.baseline_plan_path = os.path.join(cls.tmp_dir, "baseline-plan.json")
        baseline_result = _run_python_script(
            RUN_TF_PLAN_SCRIPT,
            [
                "--terraform-dir", TERRAFORM_DIR,
                "--output", cls.baseline_plan_path,
            ],
        )
        assert baseline_result.returncode == 0, (
            f"baseline plan generation failed: {baseline_result.stderr}"
        )

        # Remediated Plan: generated from the temporary copy, now restored
        # to the baseline values by the real apply_remediation.py calls
        # above.
        cls.remediated_plan_path = os.path.join(cls.tmp_dir, "remediated-plan.json")
        remediated_result = _run_python_script(
            RUN_TF_PLAN_SCRIPT,
            [
                "--terraform-dir", cls.tmp_dir,
                "--output", cls.remediated_plan_path,
            ],
        )
        assert remediated_result.returncode == 0, (
            f"remediated plan generation failed: {remediated_result.stderr}"
        )

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmp_dir, ignore_errors=True)

    def test_remediation_actually_restored_baseline_values(self):
        """Sanity check on the setup itself: the temporary main.tf copy no
        longer contains the injected unsafe values after remediation."""
        self.assertNotIn("0.0.0.0/0", self.remediated_main_tf_content)
        self.assertIn("desired_count       = 3", self.remediated_main_tf_content)

    def test_remediated_plan_artifact_was_generated(self):
        """The Remediated Plan is a real Terraform plan JSON artifact on
        disk, not a fixture or a fabricated value."""
        self.assertTrue(os.path.isfile(self.remediated_plan_path))
        with open(self.remediated_plan_path) as plan_file:
            plan = json.load(plan_file)
        self.assertIn("resource_changes", plan)

    @unittest.skipUnless(
        KIRO_CLI,
        "kiro-cli is not on PATH; skipping the live Security Reviewer "
        "Remediated Plan PASS verdict assertion (Requirement 12.8, 12.10). "
        "The deterministic remediation/plan-generation assertions above "
        "still run and do not require kiro-cli.",
    )
    def test_security_reviewer_passes_on_remediated_plan(self):
        verdict = _invoke_reviewer(
            "security-reviewer", self.baseline_plan_path, self.remediated_plan_path
        )
        self.assertEqual(verdict.get("status"), "PASS")
        self.assertEqual(verdict.get("findings"), [])

    @unittest.skipUnless(
        KIRO_CLI,
        "kiro-cli is not on PATH; skipping the live Reliability Reviewer "
        "Remediated Plan PASS verdict assertion (Requirement 12.8, 12.10). "
        "The deterministic remediation/plan-generation assertions above "
        "still run and do not require kiro-cli.",
    )
    def test_reliability_reviewer_passes_on_remediated_plan(self):
        verdict = _invoke_reviewer(
            "reliability-reviewer", self.baseline_plan_path, self.remediated_plan_path
        )
        self.assertEqual(verdict.get("status"), "PASS")
        self.assertEqual(verdict.get("findings"), [])


if __name__ == "__main__":
    unittest.main()
