#!/usr/bin/env python3
"""Remove stale run-specific ChangeGuard artifacts before a new run.

`artifacts/baseline-plan.json` is intentionally persistent (per design.md's
Baseline Lifecycle -- it must exist BEFORE a review run starts and is never
regenerated by the review workflow itself) and is NEVER touched by this
script.

Every other ChangeGuard workflow artifact is run-specific: if a prior run's
copy of one of these files is still on disk when a new run starts, a
downstream consumer (e.g. `scripts/changeguard_launch.py` deciding whether
Stage B needs to be planned, by checking for
`artifacts/change-blocked-result.json`) could mistake it for the current
run's outcome. `scripts/aggregate_review.py`'s own PASS branch already
removes `change-blocked-result.json` specifically as one layer of defense;
this script is the second, broader layer, run once at the start of a
ChangeGuard invocation (via `scripts/changeguard_launch.py`), covering
every run-specific artifact in one place.

This script uses ONLY `os.remove` against a fixed, explicit allow-list of
exact file paths -- never `shutil.rmtree`, never a glob, never a shell
`rm`. Absence of any listed file is not an error. No path outside the
allow-list is ever considered, so this script cannot be used to delete
anything else in the repository regardless of how it is invoked.

CLI contract:

    python3 scripts/cleanup_run_artifacts.py [--artifacts-dir <path>]

Exits 0 unconditionally (cleanup of already-absent files is success, not
failure) unless an unexpected OS-level error occurs while removing a file
that does exist (e.g. a permissions error), in which case it exits
non-zero with a diagnostic -- fail-loud rather than silently leaving a
stale artifact behind.
"""

import argparse
import os
import sys

# Explicit allow-list of exact, run-specific artifact filenames. This is
# the ONLY set of paths this script will ever remove. Deliberately does
# NOT include "baseline-plan.json" -- seeing it added here in a future
# edit should be treated as a regression against the Baseline Lifecycle
# requirement (design.md; steering doc), not a routine addition.
RUN_SPECIFIC_ARTIFACT_NAMES = (
    "candidate-plan.json",
    "security-review-result.json",
    "reliability-review-result.json",
    "change-blocked-result.json",
    "remediation-result.json",
    "remediated-plan.json",
    "security-remediated-review-result.json",
    "reliability-remediated-review-result.json",
    "final-verdict.json",
)

PRESERVED_ARTIFACT_NAME = "baseline-plan.json"


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        prog="cleanup_run_artifacts.py",
        description=(
            "Remove stale run-specific ChangeGuard artifacts (never "
            "baseline-plan.json) using an explicit allow-list of exact "
            "file names. No recursive deletion, no shell rm."
        ),
    )
    parser.add_argument(
        "--artifacts-dir",
        default="artifacts",
        help="Directory containing ChangeGuard's artifacts/*.json files (default: artifacts).",
    )
    return parser.parse_args(argv)


def cleanup_run_artifacts(artifacts_dir):
    """Remove every allow-listed run-specific artifact under `artifacts_dir`.

    Returns the list of paths that were actually removed (for reporting).
    Never touches PRESERVED_ARTIFACT_NAME. Never touches any path outside
    RUN_SPECIFIC_ARTIFACT_NAMES.
    """
    removed = []
    for name in RUN_SPECIFIC_ARTIFACT_NAMES:
        assert name != PRESERVED_ARTIFACT_NAME  # structural guard, not a runtime input check
        path = os.path.join(artifacts_dir, name)
        try:
            os.remove(path)
        except FileNotFoundError:
            continue
        removed.append(path)
    return removed


def main(argv=None):
    args = parse_args(argv)
    try:
        removed = cleanup_run_artifacts(args.artifacts_dir)
    except OSError as exc:
        print(f"cleanup_run_artifacts.py: failed to remove a stale artifact: {exc}", file=sys.stderr)
        return 1

    for path in removed:
        print(f"removed stale artifact: {path}")
    if not removed:
        print("no stale run-specific artifacts found")
    return 0


if __name__ == "__main__":
    sys.exit(main())
